### ISSUE TITLE
hitokoto plugin needs jq to work

### ISSUE THREAD

**Issue by liwuhou** [derry96/hitokoto#3]
是缺少zsh的某个插件吗

**Comment by liwuhou** [comment]
Mac 15.10.27 brew install 了jq 还是不行

**Comment by liwuhou** [comment]
重启了终端 可以了 😂

**Comment by bd-dxg** [comment]
> Mac 15.10.27 brew install 了jq 还是不行

请教这个jq是什么  我不想安装brew
